// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_user_db.sql

package database

import (
	"context"
)

const resetUserDB = `-- name: ResetUserDB :exec
Delete FROM users WHERE id IS NOT NULL
`

func (q *Queries) ResetUserDB(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUserDB)
	return err
}
