// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserAuthentication = `-- name: UpdateUserAuthentication :one
UPDATE users
SET email = $2, password = $3
where id = $1
RETURNING id, created_at, updated_at, email, password, is_chirpy_red
`

type UpdateUserAuthenticationParams struct {
	ID       uuid.UUID
	Email    string
	Password string
}

func (q *Queries) UpdateUserAuthentication(ctx context.Context, arg UpdateUserAuthenticationParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAuthentication, arg.ID, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.IsChirpyRed,
	)
	return i, err
}
